### ISSUE TITLE
Feature request: Escaping slashes in the endpoint middleware

### ISSUE THREAD

**Issue by Qcumbeer** [TheSoftwareHouse/react-packages#13]
Hi there!
I have a proposal for escaping slashes in `apiUrl` and `endpoint` variables.

**The case is:**
When someone sets an `REACT_APP_API_URL` with trailing slash like this: `http://google.com/` and the endpoint with leading slash like this: `/some/endpoint` then we get a double slash in the middle (`http://google.com//some/endpoint`).

**What I would purpose to have:**
```js
const baseUrl = apiUrl.replace(/\/$/, '');
const slug = endpoint.replace(/^\//, '');

return `${baseUrl}/${slug}`;
```

Of course, you can make it nicer 😜. Are there any standard JS functions which does the job?

This is the part of code I'm talking about:
https://github.com/TheSoftwareHouse/react-packages/blob/79767fbfcb902ab4ad5b96335a14afa266159ca5/packages/endpoint-middleware/src/middleware.js#L14

**Comment by marcin-piela** [comment]
I think that developers should stick to one convention (main url with slash and endpoint without or vice versa). Main url with trailing slash and endpoint with leading slash is a mistake. Library should not fix it.

**Comment by Qcumbeer** [comment]
I totally agree, that developers should stick to one convention and that would be great! But, it's not just my idea, but a real problem we faced many times, when eg. a devops guy or someone taking care of multiple projects doesn't remember what is the proper format. We had a case, when our client having access to the repository changed base url in env file few times, making our app crashed 😆

**Comment by marcin-piela** [comment]
Ok, so we will change building of output URL then. It will handle such cases.

**Comment by marcin-piela** [comment]
Finally resolved in @tshio/redux-api-endpoint-middleware@2.0.0 😄
